specVersion: 1.0.0
name: destore-pangolin
runner:
  node:
    name: '@subql/node'
    version: 'v1.4.1'
  query:
    name: '@subql/query'
    version: 'v1.2.1'
description: None
repository: ''
schema:
  file: ./schema.graphql
network:
  chainId: '0xce44bd16fc276f9e457b452577b6c2678e57768260012af127479fed806da7e7'
  endpoint: wss://pangolin-rpc.darwinia.network/

dataSources:
  - kind: substrate/Runtime
    startBlock: 3183743
    mapping: 
      file: ./dist/index.js
      handlers:
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
              module: utility
              method: batchAll
              success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
              module: utility
              method: batch
              success: true
        - handler: handleCall
          kind: substrate/CallHandler
          filter:
              module: system
              method: remark
              success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
              module: utility
              method: batchAll
              success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
              module: utility
              method: batch
              success: true
        - handler: handleRemark
          kind: substrate/CallHandler
          filter:
              module: system
              method: remark
              success: true  
